export type MediaType = "movie" | "series";

export interface CastMember {
  name: string;
  character: string;
}

export interface Title {
  id: number;
  key?: string;
  trailerKey?: string;
  title: string;
  type: MediaType;
  year: number;
  rating: number;
  votes: string;
  duration: string;
  runtimeMins: number;
  seasons?: number;
  episodes?: number;
  genres: string[];
  overview: string;
  tagline: string;
  poster: string;
  backdrop: string;
  cast: CastMember[];
  director: string;
  maturity: string;
  quality: "4K" | "HD" | "CAM";
  language: string;
  popularity: number;
  releaseDate: string;
  isNew?: boolean;
  isTop10?: boolean;
  comingSoon?: boolean;
  featured?: boolean;
  progress?: number;
}

/** Stable unique key across movies + series (TMDB namespaces overlap). */
export const titleKey = (t: Title): string => t.key ?? `${t.type}-${t.id}`;

const IMG = (path: string, size: "w500" | "w780" | "w1280" | "original" = "w500") =>
  `https://image.tmdb.org/t/p/${size}${path}`;

export const TITLES: Title[] = [
  {
    id: 1,
    title: "Dune: Part Two",
    type: "movie",
    year: 2024,
    rating: 8.6,
    votes: "512K",
    duration: "2h 46m",
    runtimeMins: 166,
    genres: ["Sci-Fi", "Adventure", "Drama"],
    overview:
      "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future only he can foresee.",
    tagline: "Long live the fighters.",
    poster: IMG("/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg"),
    backdrop: IMG("/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg", "w1280"),
    cast: [
      { name: "Timothée Chalamet", character: "Paul Atreides" },
      { name: "Zendaya", character: "Chani" },
      { name: "Rebecca Ferguson", character: "Lady Jessica" },
      { name: "Austin Butler", character: "Feyd-Rautha" },
      { name: "Florence Pugh", character: "Princess Irulan" },
      { name: "Javier Bardem", character: "Stilgar" },
    ],
    director: "Denis Villeneuve",
    maturity: "PG-13",
    quality: "4K",
    language: "English",
    popularity: 98,
    releaseDate: "2024-03-01",
    isTop10: true,
    featured: true,
    progress: 62,
  },
  {
    id: 2,
    title: "Oppenheimer",
    type: "movie",
    year: 2023,
    rating: 8.4,
    votes: "890K",
    duration: "3h 0m",
    runtimeMins: 180,
    genres: ["Drama", "History", "Thriller"],
    overview:
      "The story of J. Robert Oppenheimer and his pivotal role in the development of the atomic bomb — a paradoxical man who must risk destroying the world in order to save it.",
    tagline: "The world forever changes.",
    poster: IMG("/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg"),
    backdrop: IMG("/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg", "w1280"),
    cast: [
      { name: "Cillian Murphy", character: "J. Robert Oppenheimer" },
      { name: "Emily Blunt", character: "Kitty Oppenheimer" },
      { name: "Matt Damon", character: "Leslie Groves" },
      { name: "Robert Downey Jr.", character: "Lewis Strauss" },
      { name: "Florence Pugh", character: "Jean Tatlock" },
    ],
    director: "Christopher Nolan",
    maturity: "R",
    quality: "4K",
    language: "English",
    popularity: 95,
    releaseDate: "2023-07-21",
    isTop10: true,
    featured: true,
  },
  {
    id: 3,
    title: "The Last of Us",
    type: "series",
    year: 2023,
    rating: 8.8,
    votes: "640K",
    duration: "2 Seasons",
    runtimeMins: 55,
    seasons: 2,
    episodes: 16,
    genres: ["Drama", "Action", "Horror"],
    overview:
      "Twenty years after a fungal outbreak destroys modern civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope.",
    tagline: "Endure and survive.",
    poster: IMG("/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg"),
    backdrop: IMG("/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg", "w1280"),
    cast: [
      { name: "Pedro Pascal", character: "Joel Miller" },
      { name: "Bella Ramsey", character: "Ellie Williams" },
      { name: "Anna Torv", character: "Tess" },
      { name: "Gabriel Luna", character: "Tommy" },
    ],
    director: "Craig Mazin",
    maturity: "TV-MA",
    quality: "4K",
    language: "English",
    popularity: 97,
    releaseDate: "2023-01-15",
    isTop10: true,
    featured: true,
    progress: 34,
  },
  {
    id: 4,
    title: "John Wick: Chapter 4",
    type: "movie",
    year: 2023,
    rating: 7.7,
    votes: "402K",
    duration: "2h 49m",
    runtimeMins: 169,
    genres: ["Action", "Thriller", "Crime"],
    overview:
      "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face a new enemy with powerful alliances across the globe.",
    tagline: "No way back. One way out.",
    poster: IMG("/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg"),
    backdrop: IMG("/h8gHn0OzBoaefsYseUByqsmEDMY.jpg", "w1280"),
    cast: [
      { name: "Keanu Reeves", character: "John Wick" },
      { name: "Donnie Yen", character: "Caine" },
      { name: "Bill Skarsgård", character: "Marquis de Gramont" },
      { name: "Ian McShane", character: "Winston" },
    ],
    director: "Chad Stahelski",
    maturity: "R",
    quality: "4K",
    language: "English",
    popularity: 91,
    releaseDate: "2023-03-24",
    isTop10: true,
    featured: true,
  },
  {
    id: 5,
    title: "Stranger Things",
    type: "series",
    year: 2016,
    rating: 8.7,
    votes: "1.8M",
    duration: "5 Seasons",
    runtimeMins: 51,
    seasons: 5,
    episodes: 42,
    genres: ["Sci-Fi", "Drama", "Mystery"],
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces — and one strange little girl.",
    tagline: "The world is turning upside down.",
    poster: IMG("/49WJfeN0moxb9IPfGn8AIqMGskD.jpg"),
    backdrop: IMG("/56v2KjBlU4XaOv9rVYEQypROD7P.jpg", "w1280"),
    cast: [
      { name: "Millie Bobby Brown", character: "Eleven" },
      { name: "Finn Wolfhard", character: "Mike Wheeler" },
      { name: "David Harbour", character: "Jim Hopper" },
      { name: "Winona Ryder", character: "Joyce Byers" },
    ],
    director: "The Duffer Brothers",
    maturity: "TV-14",
    quality: "4K",
    language: "English",
    popularity: 96,
    releaseDate: "2016-07-15",
    isTop10: true,
    featured: true,
    progress: 81,
  },
  {
    id: 6,
    title: "Interstellar",
    type: "movie",
    year: 2014,
    rating: 8.7,
    votes: "2.1M",
    duration: "2h 49m",
    runtimeMins: 169,
    genres: ["Sci-Fi", "Adventure", "Drama"],
    overview:
      "With Earth becoming uninhabitable, a team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival.",
    tagline: "Mankind was born on Earth. It was never meant to die here.",
    poster: IMG("/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg"),
    backdrop: IMG("/pbrkL804c8yAv3zBZR4QPEafpAR.jpg", "w1280"),
    cast: [
      { name: "Matthew McConaughey", character: "Cooper" },
      { name: "Anne Hathaway", character: "Brand" },
      { name: "Jessica Chastain", character: "Murph" },
      { name: "Michael Caine", character: "Professor Brand" },
    ],
    director: "Christopher Nolan",
    maturity: "PG-13",
    quality: "4K",
    language: "English",
    popularity: 93,
    releaseDate: "2014-11-07",
    isTop10: true,
  },
  {
    id: 7,
    title: "The Batman",
    type: "movie",
    year: 2022,
    rating: 7.8,
    votes: "620K",
    duration: "2h 56m",
    runtimeMins: 176,
    genres: ["Action", "Crime", "Mystery"],
    overview:
      "In his second year of fighting crime, Batman uncovers corruption in Gotham City while pursuing the sadistic Riddler.",
    tagline: "Unmask the truth.",
    poster: IMG("/74xTEgt7R36Fpooo50r9T25onhq.jpg"),
    backdrop: IMG("/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg", "w1280"),
    cast: [
      { name: "Robert Pattinson", character: "Bruce Wayne" },
      { name: "Zoë Kravitz", character: "Selina Kyle" },
      { name: "Paul Dano", character: "The Riddler" },
      { name: "Colin Farrell", character: "Oz Cobblepot" },
    ],
    director: "Matt Reeves",
    maturity: "PG-13",
    quality: "4K",
    language: "English",
    popularity: 89,
    releaseDate: "2022-03-04",
    isTop10: true,
  },
  {
    id: 8,
    title: "Breaking Bad",
    type: "series",
    year: 2008,
    rating: 9.5,
    votes: "2.4M",
    duration: "5 Seasons",
    runtimeMins: 49,
    seasons: 5,
    episodes: 62,
    genres: ["Drama", "Crime", "Thriller"],
    overview:
      "A high-school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing methamphetamine to secure his family's future.",
    tagline: "All hail the king.",
    poster: IMG("/ggFHVNu6YYI5L9pCfOacjizRGt.jpg"),
    backdrop: IMG("/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg", "w1280"),
    cast: [
      { name: "Bryan Cranston", character: "Walter White" },
      { name: "Aaron Paul", character: "Jesse Pinkman" },
      { name: "Anna Gunn", character: "Skyler White" },
      { name: "Bob Odenkirk", character: "Saul Goodman" },
    ],
    director: "Vince Gilligan",
    maturity: "TV-MA",
    quality: "HD",
    language: "English",
    popularity: 94,
    releaseDate: "2008-01-20",
  },
  {
    id: 9,
    title: "Spider-Man: No Way Home",
    type: "movie",
    year: 2021,
    rating: 8.0,
    votes: "780K",
    duration: "2h 28m",
    runtimeMins: 148,
    genres: ["Action", "Adventure", "Sci-Fi"],
    overview:
      "When his identity is revealed, Peter Parker asks Doctor Strange for help, accidentally unleashing dangerous foes from every universe.",
    tagline: "The Multiverse unleashed.",
    poster: IMG("/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg"),
    backdrop: IMG("/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg", "w1280"),
    cast: [
      { name: "Tom Holland", character: "Peter Parker" },
      { name: "Zendaya", character: "MJ" },
      { name: "Benedict Cumberbatch", character: "Doctor Strange" },
      { name: "Willem Dafoe", character: "Green Goblin" },
    ],
    director: "Jon Watts",
    maturity: "PG-13",
    quality: "4K",
    language: "English",
    popularity: 90,
    releaseDate: "2021-12-17",
    isTop10: true,
  },
  {
    id: 10,
    title: "Wednesday",
    type: "series",
    year: 2022,
    rating: 8.5,
    votes: "390K",
    duration: "2 Seasons",
    runtimeMins: 45,
    seasons: 2,
    episodes: 16,
    genres: ["Comedy", "Fantasy", "Mystery"],
    overview:
      "Wednesday Addams investigates a monstrous mystery plaguing Nevermore Academy while mastering her emerging psychic ability.",
    tagline: "Misery loves company.",
    poster: IMG("/9PFonBhy4cQy7Jz20NpMygczOkv.jpg"),
    backdrop: IMG("/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg", "w1280"),
    cast: [
      { name: "Jenna Ortega", character: "Wednesday Addams" },
      { name: "Emma Myers", character: "Enid Sinclair" },
      { name: "Catherine Zeta-Jones", character: "Morticia Addams" },
      { name: "Luis Guzmán", character: "Gomez Addams" },
    ],
    director: "Tim Burton",
    maturity: "TV-14",
    quality: "4K",
    language: "English",
    popularity: 92,
    releaseDate: "2022-11-23",
    isNew: true,
    progress: 12,
  },
  {
    id: 11,
    title: "Avengers: Endgame",
    type: "movie",
    year: 2019,
    rating: 8.2,
    votes: "1.3M",
    duration: "3h 1m",
    runtimeMins: 181,
    genres: ["Action", "Adventure", "Sci-Fi"],
    overview:
      "After the devastating events of Infinity War, the remaining Avengers assemble once more to reverse Thanos' actions and restore balance to the universe.",
    tagline: "Part of the journey is the end.",
    poster: IMG("/or06FN3Dka5tukK1e9sl16pB3iy.jpg"),
    backdrop: IMG("/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg", "w1280"),
    cast: [
      { name: "Robert Downey Jr.", character: "Tony Stark" },
      { name: "Chris Evans", character: "Steve Rogers" },
      { name: "Scarlett Johansson", character: "Natasha Romanoff" },
      { name: "Chris Hemsworth", character: "Thor" },
    ],
    director: "Anthony & Joe Russo",
    maturity: "PG-13",
    quality: "4K",
    language: "English",
    popularity: 88,
    releaseDate: "2019-04-26",
  },
  {
    id: 12,
    title: "Blade Runner 2049",
    type: "movie",
    year: 2017,
    rating: 8.0,
    votes: "640K",
    duration: "2h 44m",
    runtimeMins: 164,
    genres: ["Sci-Fi", "Drama", "Mystery"],
    overview:
      "A young blade runner's discovery of a long-buried secret leads him to track down former blade runner Rick Deckard, who's been missing for thirty years.",
    tagline: "There's still a page left.",
    poster: IMG("/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg"),
    backdrop: IMG("/ilRyazdMJwN05exqhwK4tMKBYZs.jpg", "w1280"),
    cast: [
      { name: "Ryan Gosling", character: "K" },
      { name: "Harrison Ford", character: "Rick Deckard" },
      { name: "Ana de Armas", character: "Joi" },
      { name: "Jared Leto", character: "Niander Wallace" },
    ],
    director: "Denis Villeneuve",
    maturity: "R",
    quality: "4K",
    language: "English",
    popularity: 82,
    releaseDate: "2017-10-06",
  },
  {
    id: 13,
    title: "Top Gun: Maverick",
    type: "movie",
    year: 2022,
    rating: 8.2,
    votes: "720K",
    duration: "2h 10m",
    runtimeMins: 130,
    genres: ["Action", "Drama"],
    overview:
      "After thirty years, Maverick is still pushing the envelope as a top naval aviator, and must confront ghosts of his past when he trains a new squad of graduates.",
    tagline: "Feel the need... The need for speed.",
    poster: IMG("/62HCnUTziyWcpDaBO2i1DX17ljH.jpg"),
    backdrop: IMG("/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg", "w1280"),
    cast: [
      { name: "Tom Cruise", character: "Maverick" },
      { name: "Miles Teller", character: "Rooster" },
      { name: "Jennifer Connelly", character: "Penny Benjamin" },
      { name: "Val Kilmer", character: "Iceman" },
    ],
    director: "Joseph Kosinski",
    maturity: "PG-13",
    quality: "4K",
    language: "English",
    popularity: 87,
    releaseDate: "2022-05-27",
  },
  {
    id: 14,
    title: "Parasite",
    type: "movie",
    year: 2019,
    rating: 8.5,
    votes: "1.1M",
    duration: "2h 12m",
    runtimeMins: 132,
    genres: ["Thriller", "Drama", "Comedy"],
    overview:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    tagline: "Act like you own the place.",
    poster: IMG("/7IiTTgloJzvGI1TAYymCfbfl3v.jpg"),
    backdrop: IMG("/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg", "w1280"),
    cast: [
      { name: "Song Kang-ho", character: "Kim Ki-taek" },
      { name: "Lee Sun-kyun", character: "Park Dong-ik" },
      { name: "Cho Yeo-jeong", character: "Choi Yeon-gyo" },
      { name: "Choi Woo-shik", character: "Kim Ki-woo" },
    ],
    director: "Bong Joon Ho",
    maturity: "R",
    quality: "4K",
    language: "Korean",
    popularity: 85,
    releaseDate: "2019-11-08",
  },
  {
    id: 15,
    title: "The Dark Knight",
    type: "movie",
    year: 2008,
    rating: 9.0,
    votes: "2.9M",
    duration: "2h 32m",
    runtimeMins: 152,
    genres: ["Action", "Crime", "Drama"],
    overview:
      "Batman raises the stakes in his war on crime, but the Joker — a criminal mastermind — plunges Gotham into anarchy and forces the Dark Knight ever closer to crossing the line.",
    tagline: "Why so serious?",
    poster: IMG("/qJ2tW6WMUDux911r6m7haRef0WH.jpg"),
    backdrop: IMG("/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg", "w1280"),
    cast: [
      { name: "Christian Bale", character: "Bruce Wayne" },
      { name: "Heath Ledger", character: "Joker" },
      { name: "Aaron Eckhart", character: "Harvey Dent" },
      { name: "Michael Caine", character: "Alfred" },
    ],
    director: "Christopher Nolan",
    maturity: "PG-13",
    quality: "4K",
    language: "English",
    popularity: 89,
    releaseDate: "2008-07-18",
  },
  {
    id: 16,
    title: "The Boys",
    type: "series",
    year: 2019,
    rating: 8.5,
    votes: "610K",
    duration: "4 Seasons",
    runtimeMins: 60,
    seasons: 4,
    episodes: 32,
    genres: ["Action", "Comedy", "Crime"],
    overview:
      "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers, backed by a ruthless corporation.",
    tagline: "Never meet your heroes.",
    poster: IMG("/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg"),
    backdrop: IMG("/mGVrXeIjyecj6TKmwPVpHlscEmw.jpg", "w1280"),
    cast: [
      { name: "Karl Urban", character: "Billy Butcher" },
      { name: "Antony Starr", character: "Homelander" },
      { name: "Jack Quaid", character: "Hughie Campbell" },
      { name: "Erin Moriarty", character: "Starlight" },
    ],
    director: "Eric Kripke",
    maturity: "TV-MA",
    quality: "4K",
    language: "English",
    popularity: 86,
    releaseDate: "2019-07-26",
    isNew: true,
  },
  {
    id: 17,
    title: "Inception",
    type: "movie",
    year: 2010,
    rating: 8.8,
    votes: "2.6M",
    duration: "2h 28m",
    runtimeMins: 148,
    genres: ["Sci-Fi", "Action", "Thriller"],
    overview:
      "A skilled thief who steals secrets from deep within the subconscious is offered a chance to have his criminal history erased by planting an idea into a target's mind.",
    tagline: "Your mind is the scene of the crime.",
    poster: IMG("/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg"),
    backdrop: IMG("/s3TBrRGB1iav7gFOCNx3H31MoES.jpg", "w1280"),
    cast: [
      { name: "Leonardo DiCaprio", character: "Cobb" },
      { name: "Joseph Gordon-Levitt", character: "Arthur" },
      { name: "Elliot Page", character: "Ariadne" },
      { name: "Tom Hardy", character: "Eames" },
    ],
    director: "Christopher Nolan",
    maturity: "PG-13",
    quality: "4K",
    language: "English",
    popularity: 90,
    releaseDate: "2010-07-16",
  },
  {
    id: 18,
    title: "Joker",
    type: "movie",
    year: 2019,
    rating: 8.2,
    votes: "1.5M",
    duration: "2h 2m",
    runtimeMins: 122,
    genres: ["Crime", "Drama", "Thriller"],
    overview:
      "A failed comedian, isolated and disregarded by society, begins a slow descent into madness as he transforms into the criminal mastermind known as the Joker.",
    tagline: "Put on a happy face.",
    poster: IMG("/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg"),
    backdrop: IMG("/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg", "w1280"),
    cast: [
      { name: "Joaquin Phoenix", character: "Arthur Fleck" },
      { name: "Robert De Niro", character: "Murray Franklin" },
      { name: "Zazie Beetz", character: "Sophie Dumond" },
    ],
    director: "Todd Phillips",
    maturity: "R",
    quality: "4K",
    language: "English",
    popularity: 84,
    releaseDate: "2019-10-04",
  },
  {
    id: 19,
    title: "Avatar: The Way of Water",
    type: "movie",
    year: 2022,
    rating: 7.6,
    votes: "480K",
    duration: "3h 12m",
    runtimeMins: 192,
    genres: ["Sci-Fi", "Adventure", "Action"],
    overview:
      "Jake Sully lives with his newfound family on Pandora. When an ancient threat resurfaces, he must fight a difficult war against the humans.",
    tagline: "Return to Pandora.",
    poster: IMG("/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg"),
    backdrop: IMG("/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg", "w1280"),
    cast: [
      { name: "Sam Worthington", character: "Jake Sully" },
      { name: "Zoe Saldaña", character: "Neytiri" },
      { name: "Sigourney Weaver", character: "Kiri" },
      { name: "Kate Winslet", character: "Ronal" },
    ],
    director: "James Cameron",
    maturity: "PG-13",
    quality: "4K",
    language: "English",
    popularity: 83,
    releaseDate: "2022-12-16",
  },
  {
    id: 20,
    title: "House of the Dragon",
    type: "series",
    year: 2022,
    rating: 8.4,
    votes: "420K",
    duration: "2 Seasons",
    runtimeMins: 60,
    seasons: 2,
    episodes: 18,
    genres: ["Drama", "Fantasy", "Action"],
    overview:
      "The Targaryen dynasty at the height of its power, and the beginning of the end — a civil war of dragons known as the Dance of the Dragons.",
    tagline: "Fire and blood.",
    poster: IMG("/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg"),
    backdrop: IMG("/1R68vl3d5s86JsS2NPjl8UoMqIS.jpg", "w1280"),
    cast: [
      { name: "Paddy Considine", character: "King Viserys" },
      { name: "Emma D'Arcy", character: "Rhaenyra Targaryen" },
      { name: "Matt Smith", character: "Daemon Targaryen" },
      { name: "Olivia Cooke", character: "Alicent Hightower" },
    ],
    director: "Ryan Condal",
    maturity: "TV-MA",
    quality: "4K",
    language: "English",
    popularity: 88,
    releaseDate: "2022-08-21",
    isNew: true,
  },
  {
    id: 21,
    title: "Whiplash",
    type: "movie",
    year: 2014,
    rating: 8.5,
    votes: "1.1M",
    duration: "1h 46m",
    runtimeMins: 106,
    genres: ["Drama", "Music"],
    overview:
      "A promising young drummer enrolls at a cut-throat music conservatory where his mentor will stop at nothing to realize a student's potential.",
    tagline: "The road to greatness can take you to the edge.",
    poster: IMG("/7fn624j5lj3xTme2SgiLCeuedmO.jpg"),
    backdrop: IMG("/6bbZ6XyvgfjhQwbplnUh1LSj1ky.jpg", "w1280"),
    cast: [
      { name: "Miles Teller", character: "Andrew Neiman" },
      { name: "J.K. Simmons", character: "Terence Fletcher" },
      { name: "Melissa Benoist", character: "Nicole" },
    ],
    director: "Damien Chazelle",
    maturity: "R",
    quality: "HD",
    language: "English",
    popularity: 78,
    releaseDate: "2014-10-10",
  },
  {
    id: 22,
    title: "Mad Max: Fury Road",
    type: "movie",
    year: 2015,
    rating: 8.1,
    votes: "1.1M",
    duration: "2h 0m",
    runtimeMins: 120,
    genres: ["Action", "Sci-Fi", "Adventure"],
    overview:
      "In a post-apocalyptic wasteland, Max joins the fearless Furiosa as she flees a tyrant who controls the land's water — igniting a high-octane road war.",
    tagline: "What a lovely day.",
    poster: IMG("/hA2ple9q4qnwxp3hKVNhroipsir.jpg"),
    backdrop: IMG("/tbhdm8UJAb4ViCTsulYFL3lxMCd.jpg", "w1280"),
    cast: [
      { name: "Tom Hardy", character: "Max Rockatansky" },
      { name: "Charlize Theron", character: "Imperator Furiosa" },
      { name: "Nicholas Hoult", character: "Nux" },
    ],
    director: "George Miller",
    maturity: "R",
    quality: "4K",
    language: "English",
    popularity: 80,
    releaseDate: "2015-05-15",
  },
  {
    id: 23,
    title: "Deadpool & Wolverine",
    type: "movie",
    year: 2024,
    rating: 7.6,
    votes: "380K",
    duration: "2h 8m",
    runtimeMins: 128,
    genres: ["Action", "Comedy", "Sci-Fi"],
    overview:
      "A listless Wade Wilson toils away in civilian life. But when his homeworld faces an existential threat, he must suit up and convince a reluctant Wolverine to help save his universe.",
    tagline: "Come together.",
    poster: IMG("/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg"),
    backdrop: IMG("/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg", "w1280"),
    cast: [
      { name: "Ryan Reynolds", character: "Wade Wilson" },
      { name: "Hugh Jackman", character: "Logan / Wolverine" },
      { name: "Emma Corrin", character: "Cassandra Nova" },
    ],
    director: "Shawn Levy",
    maturity: "R",
    quality: "4K",
    language: "English",
    popularity: 93,
    releaseDate: "2024-07-26",
    isNew: true,
    isTop10: true,
  },
  {
    id: 24,
    title: "Inside Out 2",
    type: "movie",
    year: 2024,
    rating: 7.6,
    votes: "210K",
    duration: "1h 36m",
    runtimeMins: 96,
    genres: ["Animation", "Comedy", "Family"],
    overview:
      "Riley enters puberty and brand-new, more complex emotions move into headquarters — led by Anxiety — turning Joy's world upside down.",
    tagline: "Make room for new feelings.",
    poster: IMG("/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg"),
    backdrop: IMG("/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg", "w1280"),
    cast: [
      { name: "Amy Poehler", character: "Joy (voice)" },
      { name: "Maya Hawke", character: "Anxiety (voice)" },
      { name: "Kensington Tallman", character: "Riley (voice)" },
    ],
    director: "Kelsey Mann",
    maturity: "PG",
    quality: "4K",
    language: "English",
    popularity: 87,
    releaseDate: "2024-06-14",
    isNew: true,
  },
  {
    id: 25,
    title: "The Godfather",
    type: "movie",
    year: 1972,
    rating: 9.2,
    votes: "2.0M",
    duration: "2h 55m",
    runtimeMins: 175,
    genres: ["Crime", "Drama"],
    overview:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant youngest son.",
    tagline: "An offer you can't refuse.",
    poster: IMG("/3bhkrj58Vtu7enYsRolD1fZdja1.jpg"),
    backdrop: IMG("/tmU7GeKVybMWFButWEGl2M4GeiP.jpg", "w1280"),
    cast: [
      { name: "Marlon Brando", character: "Vito Corleone" },
      { name: "Al Pacino", character: "Michael Corleone" },
      { name: "James Caan", character: "Sonny Corleone" },
      { name: "Robert Duvall", character: "Tom Hagen" },
    ],
    director: "Francis Ford Coppola",
    maturity: "R",
    quality: "4K",
    language: "English",
    popularity: 79,
    releaseDate: "1972-03-24",
  },
  {
    id: 26,
    title: "Pulp Fiction",
    type: "movie",
    year: 1994,
    rating: 8.9,
    votes: "2.2M",
    duration: "2h 34m",
    runtimeMins: 154,
    genres: ["Crime", "Drama", "Thriller"],
    overview:
      "The lives of two mob hitmen, a boxer, a gangster's wife and a pair of diner bandits intertwine in four tales of violence and redemption.",
    tagline: "You won't know the facts until you've seen the fiction.",
    poster: IMG("/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg"),
    backdrop: IMG("/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg", "w1280"),
    cast: [
      { name: "John Travolta", character: "Vincent Vega" },
      { name: "Samuel L. Jackson", character: "Jules Winnfield" },
      { name: "Uma Thurman", character: "Mia Wallace" },
      { name: "Bruce Willis", character: "Butch Coolidge" },
    ],
    director: "Quentin Tarantino",
    maturity: "R",
    quality: "4K",
    language: "English",
    popularity: 81,
    releaseDate: "1994-10-14",
  },
  {
    id: 27,
    title: "Loki",
    type: "series",
    year: 2021,
    rating: 8.2,
    votes: "380K",
    duration: "2 Seasons",
    runtimeMins: 52,
    seasons: 2,
    episodes: 12,
    genres: ["Sci-Fi", "Fantasy", "Adventure"],
    overview:
      "The mercurial God of Mischief steps out of his brother's shadow and into a time-bending adventure with the TVA.",
    tagline: "Glorious purpose.",
    poster: IMG("/voHUmluYmKyleFkTu3lOXQG702u.jpg"),
    backdrop: IMG("/q3jHCb4dMfYF6ojikKuQUxxOKvU.jpg", "w1280"),
    cast: [
      { name: "Tom Hiddleston", character: "Loki" },
      { name: "Owen Wilson", character: "Mobius" },
      { name: "Sophia Di Martino", character: "Sylvie" },
    ],
    director: "Kate Herron",
    maturity: "TV-14",
    quality: "4K",
    language: "English",
    popularity: 82,
    releaseDate: "2021-06-09",
    progress: 47,
  },
  {
    id: 28,
    title: "Everything Everywhere All at Once",
    type: "movie",
    year: 2022,
    rating: 7.8,
    votes: "590K",
    duration: "2h 19m",
    runtimeMins: 139,
    genres: ["Action", "Sci-Fi", "Comedy"],
    overview:
      "An aging Chinese immigrant is swept up in an insane adventure where she alone can save the world by exploring other universes connecting with the lives she could have led.",
    tagline: "The universe is so much bigger than you realize.",
    poster: IMG("/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg"),
    backdrop: IMG("/ss0Os3uWJfQAENILHZUdX8Tt1OC.jpg", "w1280"),
    cast: [
      { name: "Michelle Yeoh", character: "Evelyn Wang" },
      { name: "Ke Huy Quan", character: "Waymond Wang" },
      { name: "Jamie Lee Curtis", character: "Deirdre" },
      { name: "Stephanie Hsu", character: "Joy Wang" },
    ],
    director: "Daniel Kwan & Daniel Scheinert",
    maturity: "R",
    quality: "4K",
    language: "English",
    popularity: 84,
    releaseDate: "2022-03-25",
  },
  {
    id: 29,
    title: "The Shawshank Redemption",
    type: "movie",
    year: 1994,
    rating: 9.3,
    votes: "2.9M",
    duration: "2h 22m",
    runtimeMins: 142,
    genres: ["Drama", "Crime"],
    overview:
      "Imprisoned for a crime he didn't commit, banker Andy Dufresne forms an unlikely friendship and discovers hope in the most hopeless of places.",
    tagline: "Fear can hold you prisoner. Hope can set you free.",
    poster: IMG("/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg"),
    backdrop: IMG("/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg", "w1280"),
    cast: [
      { name: "Tim Robbins", character: "Andy Dufresne" },
      { name: "Morgan Freeman", character: "Ellis Redding" },
      { name: "Bob Gunton", character: "Warden Norton" },
    ],
    director: "Frank Darabont",
    maturity: "R",
    quality: "4K",
    language: "English",
    popularity: 86,
    releaseDate: "1994-09-23",
  },
  {
    id: 30,
    title: "La La Land",
    type: "movie",
    year: 2016,
    rating: 8.0,
    votes: "680K",
    duration: "2h 8m",
    runtimeMins: 128,
    genres: ["Romance", "Drama", "Music"],
    overview:
      "An aspiring actress and a dedicated jazz musician struggle to make ends meet in Los Angeles while chasing their dreams — and falling in love.",
    tagline: "Here's to the ones who dream.",
    poster: IMG("/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg"),
    backdrop: IMG("/qJeU7KM4nT2C1WpOrwPcSDSIU6VG.jpg", "w1280"),
    cast: [
      { name: "Ryan Gosling", character: "Sebastian" },
      { name: "Emma Stone", character: "Mia" },
      { name: "John Legend", character: "Keith" },
    ],
    director: "Damien Chazelle",
    maturity: "PG-13",
    quality: "4K",
    language: "English",
    popularity: 77,
    releaseDate: "2016-12-09",
  },
  {
    id: 31,
    title: "Avengers: Doomsday",
    type: "movie",
    year: 2026,
    rating: 0,
    votes: "—",
    duration: "TBA",
    runtimeMins: 0,
    genres: ["Action", "Adventure", "Sci-Fi"],
    overview:
      "The Avengers assemble once more to face Victor von Doom — a threat unlike any the multiverse has ever seen. The road to Secret Wars begins.",
    tagline: "Doom is coming.",
    poster: IMG("/or06FN3Dka5tukK1e9sl16pB3iy.jpg"),
    backdrop: IMG("/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg", "w1280"),
    cast: [
      { name: "Robert Downey Jr.", character: "Victor von Doom" },
      { name: "Chris Hemsworth", character: "Thor" },
      { name: "Anthony Mackie", character: "Captain America" },
    ],
    director: "Anthony & Joe Russo",
    maturity: "PG-13",
    quality: "4K",
    language: "English",
    popularity: 99,
    releaseDate: "2026-12-18",
    comingSoon: true,
    isNew: true,
  },
  {
    id: 32,
    title: "Dune: Part Three",
    type: "movie",
    year: 2026,
    rating: 0,
    votes: "—",
    duration: "TBA",
    runtimeMins: 0,
    genres: ["Sci-Fi", "Adventure", "Drama"],
    overview:
      "Paul Atreides' journey continues as holy war spreads across the known universe in his name. The adaptation of Dune Messiah concludes Villeneuve's trilogy.",
    tagline: "The holy war begins.",
    poster: IMG("/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg"),
    backdrop: IMG("/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg", "w1280"),
    cast: [
      { name: "Timothée Chalamet", character: "Paul Atreides" },
      { name: "Zendaya", character: "Chani" },
      { name: "Florence Pugh", character: "Princess Irulan" },
    ],
    director: "Denis Villeneuve",
    maturity: "PG-13",
    quality: "4K",
    language: "English",
    popularity: 97,
    releaseDate: "2026-12-18",
    comingSoon: true,
    isNew: true,
  },
  {
    id: 33,
    title: "The Batman: Part II",
    type: "movie",
    year: 2027,
    rating: 0,
    votes: "—",
    duration: "TBA",
    runtimeMins: 0,
    genres: ["Action", "Crime", "Mystery"],
    overview:
      "Bruce Wayne returns to a flooded, fractured Gotham as a new wave of terror rises from the Penguin's criminal empire.",
    tagline: "Vengeance has a sequel.",
    poster: IMG("/74xTEgt7R36Fpooo50r9T25onhq.jpg"),
    backdrop: IMG("/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg", "w1280"),
    cast: [
      { name: "Robert Pattinson", character: "Bruce Wayne" },
      { name: "Colin Farrell", character: "Oz Cobblepot" },
    ],
    director: "Matt Reeves",
    maturity: "PG-13",
    quality: "4K",
    language: "English",
    popularity: 90,
    releaseDate: "2027-10-01",
    comingSoon: true,
  },
  {
    id: 34,
    title: "Stranger Things: Tales From '85",
    type: "series",
    year: 2026,
    rating: 0,
    votes: "—",
    duration: "1 Season",
    runtimeMins: 0,
    seasons: 1,
    episodes: 8,
    genres: ["Animation", "Sci-Fi", "Mystery"],
    overview:
      "An animated return to Hawkins in the winter of 1985, where the party faces a new interdimensional mystery between seasons of the main saga.",
    tagline: "Back to Hawkins.",
    poster: IMG("/49WJfeN0moxb9IPfGn8AIqMGskD.jpg"),
    backdrop: IMG("/56v2KjBlU4XaOv9rVYEQypROD7P.jpg", "w1280"),
    cast: [
      { name: "Millie Bobby Brown", character: "Eleven (voice)" },
      { name: "Finn Wolfhard", character: "Mike (voice)" },
    ],
    director: "The Duffer Brothers",
    maturity: "TV-PG",
    quality: "4K",
    language: "English",
    popularity: 88,
    releaseDate: "2026-10-30",
    comingSoon: true,
  },
];

export const GENRES = [
  "Action",
  "Adventure",
  "Animation",
  "Comedy",
  "Crime",
  "Drama",
  "Family",
  "Fantasy",
  "History",
  "Horror",
  "Music",
  "Mystery",
  "Romance",
  "Sci-Fi",
  "Thriller",
] as const;

export const SORT_OPTIONS = [
  { id: "popular", label: "Most Popular", desc: "Trending across the globe" },
  { id: "rating", label: "Highest Rated", desc: "Critics & audience score" },
  { id: "newest", label: "Newest First", desc: "Fresh releases on top" },
  { id: "oldest", label: "Oldest First", desc: "Classics on top" },
  { id: "az", label: "A – Z", desc: "Alphabetical order" },
  { id: "buzz", label: "Most Talked About", desc: "Most votes & buzz" },
] as const;

export type SortId = (typeof SORT_OPTIONS)[number]["id"];

export const YEAR_OPTIONS = [
  { id: "all", label: "All Years" },
  { id: "2024+", label: "2024 & Beyond" },
  { id: "2020s", label: "2020 – 2023" },
  { id: "2010s", label: "2010 – 2019" },
  { id: "2000s", label: "2000 – 2009" },
  { id: "classic", label: "Before 2000" },
] as const;

export type YearId = (typeof YEAR_OPTIONS)[number]["id"];

export const RATING_OPTIONS = [
  { id: 0, label: "Any" },
  { id: 6, label: "6+" },
  { id: 7, label: "7+" },
  { id: 8, label: "8+" },
  { id: 8.5, label: "8.5+" },
] as const;

export function matchYear(year: number, opt: YearId): boolean {
  switch (opt) {
    case "all":
      return true;
    case "2024+":
      return year >= 2024;
    case "2020s":
      return year >= 2020 && year <= 2023;
    case "2010s":
      return year >= 2010 && year <= 2019;
    case "2000s":
      return year >= 2000 && year <= 2009;
    case "classic":
      return year < 2000;
  }
}

export function sortTitles(list: Title[], sort: SortId): Title[] {
  const arr = [...list];
  switch (sort) {
    case "popular":
      return arr.sort((a, b) => b.popularity - a.popularity);
    case "rating":
      return arr.sort((a, b) => b.rating - a.rating);
    case "newest":
      return arr.sort((a, b) => b.year - a.year);
    case "oldest":
      return arr.sort((a, b) => a.year - b.year);
    case "az":
      return arr.sort((a, b) => a.title.localeCompare(b.title));
    case "buzz":
      return arr.sort((a, b) => b.popularity - a.popularity);
  }
}

/* Local fallback catalog (used when the TMDB API is unreachable).
   Keys are prefixed with "local-" so they never collide with TMDB ids. */
export const FALLBACK_TITLES: Title[] = TITLES.map((t) => ({
  ...t,
  key: `local-${t.type}-${t.id}`,
}));

export const FALLBACK_FEATURED: Title[] = FALLBACK_TITLES.filter((t) => t.featured);

export const FALLBACK_TRENDING: Title[] = FALLBACK_TITLES.filter((t) => t.isTop10).sort(
  (a, b) => b.popularity - a.popularity
);

export const FALLBACK_SPOTLIGHT: Title = [...FALLBACK_TITLES]
  .filter((t) => !t.comingSoon && t.rating > 0)
  .sort((a, b) => b.rating - a.rating)[0];

/** Attach offline keys to raw static titles so they never hit the network. */
export function asLocal(t: Title): Title {
  return t.key ? t : { ...t, key: `local-${t.type}-${t.id}` };
}
